Shop/djangoshop/djangoshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings                    #Для определяния этапа отладки
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ecomapp.urls')),
]

if settings.DEBUG:                                                                          #Условие определяющие путь к статическим файлам во время разработки
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Shop/djangoshop/ecomapp/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from ecomapp.views import (
	base_view,
	category_view,
	product_view, cart_view,
	add_to_cart,
	remove_from_cart,
	change_item_qty,
	checkout_view,
	order_create_view,
	make_order_view
	)

urlpatterns = [
	url(r'^$', base_view, name='base'),
	url(r'^cart/$', cart_view, name='cart'),
	url(r'^remove_from_cart/$', remove_from_cart, name='remove_from_cart'),
	url(r'^add_to_cart/$', add_to_cart, name='add_to_cart'),
	url(r'^change_item_qty/$', change_item_qty, name='change_item_qty'),
	url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
	url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
	url(r'^checkout/$', checkout_view, name='checkout_view'),
	url(r'^order/$', order_create_view, name='create_order'),
	url(r'^make_order/$', make_order_view, name='make_order'),
	url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you')
]

Shop/djangoshop/ecomapp/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from transliterate import translit
from decimal import Decimal
from django.conf import settings
# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
         return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(instance.name, reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
         return self.name


def image_folder(instance, filename):                             #Ф-ция для создания нормального имени изображения
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class ProductManager(models.Manager):                             #Переорпределение мэнеджера отвечающего за выдачу продуктов

    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)


class Product(models.Model):

    category = models.ForeignKey(Category)
    brand = models.ForeignKey(Brand)
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
         return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


class CartItem(models.Model):

    product = models.ForeignKey(Product)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    cart_id = models.PositiveIntegerField(default=0)


    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)


class Cart(models.Model):
    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()
        return

    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()
        return

    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()

ORDER_STATUS_CHOICES = (
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполняется', 'Выполняется'),
    ('Выполнен', 'Выполнен'),
    ('Отменен', 'Отменен'),
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    items = models.ManyToManyField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255, blank=True)
    buying_types = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')),
                                    default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(blank=True)
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES)

    def __str__(self):
        return 'Заказ №{0}'.format(str(self.id))

Shop/djangoshop/ecomapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils import timezone


class OrderForm(forms.Form):

    name = forms.CharField()
    last_name = forms.CharField(required=False)
    phone = forms.CharField()
    buying_type = forms.ChoiceField(widget=forms.Select(), choices=([('self', 'Самовывоз'), ('delivery', 'Доставка')]))
    date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['phone'].label = 'Контактный телефон'
        self.fields['phone'].help_text = 'Пожалуйста, указывайте реальный номер телефона, по которому можно с Вами связаться'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].label = 'Адрес доставки'
        self.fields['address'].help_text = '*Обязательно указывайте город'
        self.fields['comments'].label = 'Комментарии к заказу'
        self.fields['date'].label = 'Дата доставки'
        self.fields['date'].help_text = 'Доставка производится на следующий день послк офрмления заказа. Менеджер с вами прдварительно свяжется.'

Shop/djangoshop/ecomapp/views.py
from django.shortcuts import render
from ecomapp.models import Category, Product, Cart, CartItem, Order
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from ecomapp.forms import OrderForm
from decimal import Decimal
# Create your views here.


def base_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products,
        'cart': cart
    }
    return render(request, 'base.html', context)


def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)

    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    context = {
        'product': product,
        'categories': categories,
        'cart': cart
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    category = Category.objects.get(slug=category_slug)
    products_of_categories = Product.objects.filter(category=category)
    context = {
        'category': category,
        'products_of_categories': products_of_categories,
        'categories': categories,
        'cart': cart
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart': cart
    }
    return render(request, 'cart.html', context)


def add_to_cart(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(),
                        'cart_total_price': cart.cart_total})


def remove_from_cart(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(),
                        'cart_total_price': cart.cart_total})


def change_item_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart.change_qty(qty, item_id)
    cart_item = CartItem.objects.get(id=int(item_id))
    cart_item.cart_id = cart_id
    cart_item.save()
    return JsonResponse({'cart_total': cart.items.count(),
                         'item_total': cart_item.item_total,
                        'cart_total_price': cart.cart_total})


def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart': cart
    }
    return render(request, 'checkout.html', context)


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    context = {
        'form': form,
        'cart': cart
    }
    return render(request, 'order.html', context)


def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order()
        new_order.user = request.user
        new_order.save()
        new_order.items.add(cart)
        new_order.first_name = name
        new_order.last_name = last_name
        new_order.phone = phone
        new_order.address = address
        new_order.buying_types = buying_type
        new_order.comments = comments
        new_order.total = cart.cart_total
        new_order.save()
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))

Shop/djangoshop/ecomapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Серебрянный мир</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <style>
    .carousel-control-prev-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E");
    }

    .carousel-control-next-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
    }
  </style>
</head>


<body>

  <!-- Navigation -->
  <div class="container pb-5">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Серебрянный мир</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              {% if not request.get_full_path == '/' %}
                <li class="nav-item">
                    <div class="dropdown">
                        <div class="nav-link">
                          <a class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Категории
                          </a>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              {% for category in categories %}
                            <a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name}}</a>
                              {% endfor %}
                          </div>
                        </div>
                    </div>
                </li>
              {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li>
                  <a class="nav-link" href="{% url 'cart' %}">Корзина
                      <span class="badge badge-secondary" id="cart_count">{% if not request.session.total %} 0
                          {% else %} {{ request.session.total }} {% endif %}</span>
                  </a>
              </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <!-- Page Content -->
  {%block content%}
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Категории</h1>
        <div class="list-group">
          {% for category in categories %}
            <a href="{{category.get_absolute_url}}" class="list-group-item">{{category.name}}</a>
          {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
              {% for product in products %}
                  {% if forloop.first %}
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{{product.image.url}}" alt="First slide" style="padding-left: 260px; height: 300px">
                        <p class="text-center"><a href="{{ product.get_absolute_url }}"><button class="btn btn-primary">{{ product.title }}</button> </a></p>
                    </div>
                  {% else %}
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{{product.image.url}}" alt="Second slide" style="padding-left: 260px; height: 300px">
                        <p class="text-center"><a href="{{ product.get_absolute_url }}"><button class="btn btn-primary">{{ product.title }}</button> </a></p>
                    </div>
                  {% endif %}
              {% endfor %}
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="false" style="color: black"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="false" style="color: black;"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row mt-3">

          {% for product in products%}
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="{{product.get_absolute_url}}"><img class="card-img-top" src="{{product.image.url}}" alt=""></a>
                <div class="card-body">
                  <h5 class="card-title">
                    <a href="{{product.get_absolute_url}}">{{product.title}}</a>
                  </h5>
                  <h5>{{product.price}} руб.</h5>
                  <p class="card-text">{{product.description}}</p>
                </div>
                <div class="card-footer">
                  <a href="{{product.get_absolute_url}}"><button class="btn btn-info">Подробнее</button></a>
                </div>
              </div>
            </div>
          {% endfor%}

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->
    {%endblock content%}
  </div>
  <!-- /.container -->

  <!-- Footer -->
      <footer class="py-4 bg-dark fixed-bottom">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; Серебрянный мир 2019</p>
        </div>
        <!-- /.container -->
      </footer>

</body>

</html>

Shop/djangoshop/ecomapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <h3 class="text-center">Ваша корзина</h3>
        <br>
        {% if cart.items.count > 0 %}
            <div class="my-cart">
                <table class="table">
                    <tr>
                        <td class="text-center"><strong>Товар</strong></td>
                        <td class="text-center"><strong>Кол-во</strong></td>
                        <td class="text-center"><strong>Цена</strong></td>
                        <td class="text-center"></td>
                    </tr>
                    {% for item in cart.items.all %}
                    <tr class="cart-item-{{ item.product.id }}">
                        <td class="text-center">{{ item.product.title }}</td>
                        <td class="text-center">
                            <form action="" method="get">
                                <input type="number" name="qty"  class='cart-item-qty' data-id='{{ item.id }}'
                                       value="{{ item.qty }}" min="1" style="width: 50px;">
                            </form>
                        </td>
                        <td class="text-center" id="cart-item-total-{{ item.id }}">{{ item.item_total }} руб.</td>
                        <td class="text-center">
                            <a href="#" class="remove_from_cart" data-slug="{{ item.product.slug }}" data-id="{{ item.product.id }}">
                                <button class="btn btn-default">Удалить из корзины</button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td class="text-center"></td>
                        <td class="text-center"><strong>Итого: </strong></td>
                        <td class="text-center" id="cart-total-price"><strong>{{ cart.cart_total }} руб.</strong></td>
                        <td class="text-center"></td>
                    </tr>
                </table>
            <br>
            <a href="{% url 'checkout_view' %}" class='float-right'><button class="btn btn-info">Предварительынй заказ</button></a>
            </div>
        {% else %}
            <h3 class="text-center">Ваша корзина пуста</h3>
        {% endif %}
        <h3 class="cart-empty"></h3>
    </div>
    <script>
        $(document).ready(function() {
            $('.remove_from_cart').on('click', function(e) {
                e.preventDefault()
                product_slug = $(this).attr('data-slug')
                item_product_id = $(this).attr('data-id')
                data = {
                    product_slug: product_slug
                }
                console.log(item_product_id)
                $.ajax({
                    type: 'GET',
                    url: '{% url 'remove_from_cart' %}',
                    data: data,
                    success: function(data) {
                        $("#cart_count").html(data.cart_total)
                        $('.cart-item-'+item_product_id).css('display', 'none')
                        $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб. </strong>')
                        if(parseInt(data.cart_total) == 0){
                            $('.my-cart').css('display', 'none')
                            $('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
                        }
                    }
                })
            })
        })

        $(document).ready(function() {
            $('.cart-item-qty').on('click', function () {
                qty = $(this).val()
                item_id = $(this).attr('data-id')
                console.log(item_id, qty)
                data = {
                    qty: qty,
                    item_id: item_id
                }
                $.ajax({
                    type: 'GET',
                    url: '{% url 'change_item_qty' %}',
                    data:data,
                    success: function (data) {
                        $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' руб.')
                        $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб. </strong>')
                    }
                    
                })
            })
        })

    </script>
{%endblock content%}

Shop/djangoshop/ecomapp/templates/category.html
{%extends 'base.html'%}

{%block content%}
    <div class="container">
        <div class="col-sm-12 mt-3">
            <h2>{{ category.name }}</h2>
            <hr>
        </div>

        <div class="col-lg-9 mt-5">
            <div class="row">
              {% for product in products_of_categories%}
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card h-100">
                    <a href="{{product.get_absolute_url}}"><img class="card-img-top" src="{{product.image.url}}" alt=""></a>
                    <div class="card-body">
                      <h5 class="card-title">
                        <a href="{{product.get_absolute_url}}">{{product.title}}</a>
                      </h5>
                      <h5>{{product.price}} руб.</h5>
                      <p class="card-text">{{product.description}}</p>
                    </div>
                    <div class="card-footer">
                      <a href="{{product.get_absolute_url}}"><button class="btn btn-info">Подробнее</button></a>
                    </div>
                  </div>
                </div>
              {% endfor%}
            </div>
        </div>
    </div>
{%endblock content%}

Shop/djangoshop/ecomapp/templates/checkout.html
{%extends 'base.html'%}

{% block content %}
    <div class="container mt-3">
        <h3 class="text-center">Ваш предварительный заказ</h3>
        <br>
        <table class="table">
            <tr>
                <td class="text-center"><strong>Товар</strong></td>
                <td class="text-center"><strong>Кол-во</strong></td>
                <td class="text-center"><strong>Цена</strong></td>
                <td class="text-center"></td>
            </tr>
            {% for item in cart.items.all %}
            <tr class="cart-item-{{ item.product.id }}">
                <td class="text-center">{{ item.product.title }}</td>
                <td class="text-center">{{ item.qty }}</td>
                <td class="text-center">{{ item.item_total }} руб.</td>
                <td class="text-center"></td>
            </tr>
            {% endfor %}
            <tr>
                <td class="text-center"></td>
                <td class="text-center"><strong>Итого: </strong></td>
                <td class="text-center"><strong>{{ cart.cart_total }} руб.</strong></td>
                <td class="text-center"></td>
            </tr>
        </table>
    <a href="{% url 'create_order' %}" class='float-right'><button class="btn btn-success">Оформить заказ</button></a>
    </div>
{% endblock content %}

Shop/djangoshop/ecomapp/templates/order.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-3">
        <form action='{% url "make_order" %}' method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-4">
                    {{ form.name|as_crispy_field }}
                </div>
                <div class="col-sm-4">
                    {{ form.last_name|as_crispy_field }}
                </div>
                <div class="col-sm-4">
                    {{ form.phone|as_crispy_field }}
                </div>
            </div>
            {{ form.buying_type|as_crispy_field }}
            {{ form.address|as_crispy_field }}
            {{ form.date|as_crispy_field }}
            {{ form.comments|as_crispy_field }}
            <input type="hidden" name="_csrf" value="{% csrf_token %}" />
            <input type="submit" class="btn btn-success" value="Офрмить заказ">
        </form>
    </div>
    <script>
        $(document).ready(function () {
            $('#div_id_address').css('display', 'none')
            $('#id_buying_type').on('click', function () {
                buying_type = $(this).val()
                if(buying_type == 'delivery'){
                    $('#div_id_address').css('display', 'block')
                }else{
                    $('#div_id_address').css('display', 'none')
                }
            })
            $('#id_date_month').css('width', '100px')
            $('#id_date_month').css('display', 'inline')
            $('#id_date_year').css('width', '100px')
            $('#id_date_year').css('display', 'inline')
            $('#id_date_day').css('width', '100px')
            $('#id_date_day').css('display', 'inline')

        })
    </script>
{% endblock content %}

Shop/djangoshop/ecomapp/templates/thank_you.html
{% extends 'base.html' %}


{% block content %}
<div class="container mt-3">
    <div class='col-sm-8 col-sm-offset-2'>
        <h3 class='text-center'>Спасибо за Ваш заказ! Он принят в обработку. В ближайшее время менеджер с Вами свяжется</h3>
        <p class='text-center'><a href='/'><button class='btn btn-default'>Вернуться в каталог</button></a></p>
    </div>
</div>
{% endblock content %}